[build.env]
passthrough = [
  "CROSS_DEBUG",
  "RUST_BACKTRACE",
]

[target.aarch64-unknown-linux-gnu]
dockerfile = "./ci/Dockerfile-cross"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./ci/Dockerfile-cross"

